2024-03-11 18:39:26,815:common_utils:INFO:Updated server timestamp: 1710207567398
2024-03-11 18:39:27,097:common_utils:INFO:Updated server timestamp: 1710207567681
2024-03-11 18:39:36,218:binance_update_ads:INFO:Competitor ad - spot: 1, price: 1250922.25, base: 1214487.63, ratio: 102.99999926718068. Not enough diff: 0.03999926718068991
2024-03-11 18:39:41,231:binance_update_ads:INFO:Competitor ad - spot: 2, price: 1263067.13, base: 1214487.62, ratio: 104.00000042816409. Not enough diff: 0.04000042816409177
2024-03-11 18:39:51,621:binance_update_ads:INFO:Competitor ad - spot: 1, price: 17.09, base: 16.8, ratio: 101.72619047619047. Not enough diff: 0.03619047619046967
2024-03-11 18:40:12,958:binance_update_ads:INFO:Competitor ad - spot: 1, price: 17.34, base: 16.8, ratio: 103.21428571428571. Not enough diff: 0.04428571428570649
2024-03-11 18:40:23,285:binance_update_ads:INFO:Competitor ad - spot: 1, price: 69890.11, base: 68232.07, ratio: 102.43000102444495. Not enough diff: 0.040001024444947575
2024-03-11 18:40:32,336:common_utils:INFO:Updated server timestamp: 1710207632914
2024-03-11 18:40:32,603:common_utils:INFO:Updated server timestamp: 1710207633184
2024-03-11 18:41:19,184:binance_c2c:INFO:Message sent
2024-03-11 18:43:25,956:common_utils:INFO:Updated server timestamp: 1710207806541
2024-03-11 18:43:26,239:common_utils:INFO:Updated server timestamp: 1710207806829
2024-03-11 18:44:02,735:common_utils:INFO:Updated server timestamp: 1710207843323
2024-03-11 18:44:03,022:common_utils:INFO:Updated server timestamp: 1710207843608
2024-03-11 18:44:14,989:binance_c2c:INFO:Message sent
2024-03-11 18:45:10,992:common_utils:INFO:Updated server timestamp: 1710207911574
2024-03-11 18:45:11,242:common_utils:INFO:Updated server timestamp: 1710207911832
2024-03-11 18:45:45,265:common_utils:INFO:Updated server timestamp: 1710207945844
2024-03-11 18:45:45,529:common_utils:INFO:Updated server timestamp: 1710207946110
2024-03-11 18:45:47,325:__main__:ERROR:An error occurred: BinanceWallets.check_asset_balance() takes 2 positional arguments but 3 were given
2024-03-11 18:45:47,325:__main__:ERROR:Traceback (most recent call last):
  File "c:\Users\p7016\Documents\bpa\binance_orders.py", line 33, in binance_buy_order
    missing_balance = wallets.check_asset_balance(asset_type, btc_target)
TypeError: BinanceWallets.check_asset_balance() takes 2 positional arguments but 3 were given

2024-03-11 18:46:51,099:common_utils:INFO:Updated server timestamp: 1710208011682
2024-03-11 18:46:51,355:common_utils:INFO:Updated server timestamp: 1710208011939
2024-03-11 18:46:52,779:__main__:ERROR:An error occurred: BinanceWallets.check_asset_balance() takes 2 positional arguments but 3 were given
2024-03-11 18:46:52,779:__main__:ERROR:Traceback (most recent call last):
  File "c:\Users\p7016\Documents\bpa\binance_orders.py", line 33, in binance_buy_order
    missing_balance = wallets.check_asset_balance(asset_type, btc_target)
TypeError: BinanceWallets.check_asset_balance() takes 2 positional arguments but 3 were given

2024-03-11 18:48:03,318:common_utils:INFO:Updated server timestamp: 1710208083912
2024-03-11 18:48:03,578:common_utils:INFO:Updated server timestamp: 1710208084173
2024-03-11 18:48:05,246:__main__:INFO:Missing balance for BTC: 1.7380000000011275e-05
2024-03-11 18:48:05,246:__main__:INFO:No missing balance for BTC; 1.7380000000011275e-05
2024-03-11 18:49:14,237:common_utils:INFO:Updated server timestamp: 1710208154817
2024-03-11 18:49:14,503:common_utils:INFO:Updated server timestamp: 1710208155100
2024-03-11 18:49:15,926:__main__:INFO:Missing balance for BTC: 1.7380000000011275e-05
2024-03-11 18:49:15,926:__main__:INFO:No missing balance for BTC; 1.7380000000011275e-05
2024-03-11 18:56:57,830:common_utils:INFO:Updated server timestamp: 1710208618416
2024-03-11 18:56:58,093:common_utils:INFO:Updated server timestamp: 1710208618677
2024-03-11 19:26:58,377:common_utils:INFO:Updated server timestamp: 1710210418965
2024-03-11 19:52:11,270:binance_c2c:INFO:Message sent
2024-03-11 19:52:16,276:binance_c2c:INFO:Message sent
2024-03-11 19:52:16,276:binance_c2c:INFO:Message sent
2024-03-11 19:52:19,313:fetch_outlook:ERROR:Failed to load tokens
2024-03-11 19:52:19,313:binance_c2c:ERROR:Database operation failed, rolled back: '>=' not supported between instances of 'datetime.datetime' and 'NoneType'
Traceback (most recent call last):
  File "c:\Users\p7016\Documents\bpa\binance_c2c.py", line 58, in on_message
    await merchant_account.handle_message_by_type(connection_manager, KEY, SECRET, msg_json, msg_type, conn)
  File "c:\Users\p7016\Documents\bpa\binance_merchant_handler.py", line 27, in handle_message_by_type
    await self._handle_system_type(connection_manager, msg_json, conn, order_no, order_details, buyer_name)
  File "c:\Users\p7016\Documents\bpa\binance_merchant_handler.py", line 47, in _handle_system_type
    await handle_system_notifications(connection_manager, order_no, order_details, conn, order_status)
  File "c:\Users\p7016\Documents\bpa\binance_msg_handler.py", line 86, in handle_system_notifications
    await handle_order_status_1(connection_manager, conn, order_no, order_details)
  File "c:\Users\p7016\Documents\bpa\binance_msg_handler.py", line 62, in handle_order_status_1
    if await check_and_handle_country_restrictions(connection_manager, conn, order_no, seller_name, buyer_name, fiat):
  File "c:\Users\p7016\Documents\bpa\binance_msg_handler.py", line 31, in check_and_handle_country_restrictions
    country = await fetch_ip(order_no[-4:], seller_name)
  File "c:\Users\p7016\Documents\bpa\verify_client_ip.py", line 22, in fetch_ip
    ip = await outlook_fetch_ip(last_four_digits)
  File "c:\Users\p7016\Documents\bpa\fetch_outlook.py", line 91, in outlook_fetch_ip
    if datetime.datetime.now() >= expiration_time:
TypeError: '>=' not supported between instances of 'datetime.datetime' and 'NoneType'
2024-03-11 19:55:02,002:binance_c2c:INFO:Message sent
2024-03-11 19:55:07,030:binance_c2c:INFO:Message sent
2024-03-11 19:55:07,030:binance_c2c:INFO:Message sent
2024-03-11 19:55:10,052:fetch_outlook:ERROR:Failed to load tokens
2024-03-11 19:55:10,054:binance_c2c:ERROR:Database operation failed, rolled back: '>=' not supported between instances of 'datetime.datetime' and 'NoneType'
Traceback (most recent call last):
  File "c:\Users\p7016\Documents\bpa\binance_c2c.py", line 58, in on_message
    await merchant_account.handle_message_by_type(connection_manager, KEY, SECRET, msg_json, msg_type, conn)
  File "c:\Users\p7016\Documents\bpa\binance_merchant_handler.py", line 27, in handle_message_by_type
    await self._handle_system_type(connection_manager, msg_json, conn, order_no, order_details, buyer_name)
  File "c:\Users\p7016\Documents\bpa\binance_merchant_handler.py", line 47, in _handle_system_type
    await handle_system_notifications(connection_manager, order_no, order_details, conn, order_status)
  File "c:\Users\p7016\Documents\bpa\binance_msg_handler.py", line 86, in handle_system_notifications
    await handle_order_status_1(connection_manager, conn, order_no, order_details)
  File "c:\Users\p7016\Documents\bpa\binance_msg_handler.py", line 62, in handle_order_status_1
    if await check_and_handle_country_restrictions(connection_manager, conn, order_no, seller_name, buyer_name, fiat):
  File "c:\Users\p7016\Documents\bpa\binance_msg_handler.py", line 31, in check_and_handle_country_restrictions
    country = await fetch_ip(order_no[-4:], seller_name)
  File "c:\Users\p7016\Documents\bpa\verify_client_ip.py", line 22, in fetch_ip
    ip = await outlook_fetch_ip(last_four_digits)
  File "c:\Users\p7016\Documents\bpa\fetch_outlook.py", line 91, in outlook_fetch_ip
    if datetime.datetime.now() >= expiration_time:
TypeError: '>=' not supported between instances of 'datetime.datetime' and 'NoneType'
2024-03-11 19:56:58,673:common_utils:INFO:Updated server timestamp: 1710212219268
2024-03-11 20:07:09,822:binance_c2c:INFO:Message sent
2024-03-11 20:07:14,826:binance_c2c:INFO:Message sent
2024-03-11 20:10:01,456:binance_c2c:INFO:Message sent
2024-03-11 20:10:06,473:binance_c2c:INFO:Message sent
